=== Iemelianova/Maven/target/classes/com/solvd/data/Trips.xsd
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
  <xs:element name="name" type="xs:string"/>
  <xs:element name="from" type="xs:string"/>
  <xs:element name="to" type="xs:string"/>
  <xs:element name="transport" type="xs:string"/>
  <xs:element name="duration" type="xs:duration"/>
  <xs:element name="date" type="xs:date"/>
  <xs:element name="trip_id">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="from"/>
        <xs:element ref="to"/>
        <xs:element ref="transport"/>
        <xs:element ref="duration"/>
        <xs:element ref="date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="inside_the_country">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="trip_id" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="outside_the_country">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="trip_id" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="inside_the_country"/>
        <xs:element ref="outside_the_country"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="business_trips">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="employees"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Iemelianova/Maven/java/com/solvd/data/Business_trips.xml
<business_trips xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation = "Trips.xsd">
<employees>
<inside_the_country>
<trip_id>
<name>Leila Simonova</name>
<from>Chernivtsy</from>
<to>Kiev</to>
<transport>train</transport>
<duration>P3D</duration>
<date>2020/04/18</date>
</trip_id>
<trip_id>
<name>Svetlana Savikova</name>
<from>Kiev</from>
<to>Chernivtsy</to>
<transport>train</transport>
<duration>P1D</duration>
<date>2020/03/02</date>
</trip_id>
</inside_the_country>
<outside_the_country>
<trip_id>
<name>Ien Grigorian</name>
<from>Kiev</from>
<to>Minsk</to>
<transport>plain</transport>
<duration>P3D</duration>
<date>2020/03/06</date>
</trip_id>
</outside_the_country>
</employees>
</business_trips>
