=== Iemelianova/Maven/java/com/solvd/data/Playlist.xsd
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
<xs:element name="playlist">
   <xs:complexType>
      <xs:sequence>
	   <xs:element name="music">
	   <xs:complexType>
		  <xs:sequence>
	    <xs:element name="minor">
		 <xs:complexType>
		  <xs:sequence>
		 <xs:element name="song_id" maxOccurs="unbounded">
   <xs:complexType>
      <xs:sequence>
         <xs:element name="music_group" type="xs:string" minOccurs="0"/>
         <xs:element name="performer_name" type="xs:string" minOccurs="0"/>
         <xs:element name="album" type="xs:string"/>
         <xs:element name="song" type="xs:string"/>
		 <xs:element name="release_year" type="xs:gYear"/>
         <xs:element name="genre" type="xs:string"/>
      </xs:sequence>
   </xs:complexType>
   </xs:element>
   
   </xs:sequence>
   </xs:complexType>
  </xs:element>
  
<xs:element name="major">
		 <xs:complexType>
		  <xs:sequence>
		   <xs:element name="song_id" maxOccurs="unbounded">
   <xs:complexType>
      <xs:sequence>
         <xs:element name="music_group" type="xs:string" minOccurs="0"/>
         <xs:element name="performer_name" type="xs:string" minOccurs="0"/>
         <xs:element name="album" type="xs:string"/>
         <xs:element name="song" type="xs:string"/>
		 <xs:element name="release_year" type="xs:gYear"/>
         <xs:element name="genre" type="xs:string"/>
      </xs:sequence>
   </xs:complexType>
   </xs:element>
  </xs:sequence>
 </xs:complexType>
 </xs:element>
         
      </xs:sequence>
   </xs:complexType>
</xs:element>

 </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== Iemelianova/Maven/target/classes/com/solvd/data/Playlist.xml
<playlist xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation = "Playlist.xsd">
<music>
<minor>
<song_id>
<performer_name>Billie Eilish</performer_name>
<album>Burry a friend</album>
<song>Burry a friend</song>
<release_year>2019</release_year>
<genre>pop</genre>
</song_id>
<song_id>
<music_group>Nirvana</music_group>
<performer_name>Kurt Cobain</performer_name>
<album> MTV Unplugged in New York</album>
<song>The Man Who Sold The World </song>
<release_year>1994</release_year>
<genre>grunge, alternative</genre>
</song_id>
<song_id>
<performer_name>Stone Sour</performer_name>
<album>Come What(ever) May</album>
<song>Through The Glass</song>
<release_year>2006</release_year>
<genre>post-grunge, alternative</genre>
</song_id>
</minor>
<major>
<song_id>
<music_group>Cypress Hill</music_group>
<album>(Rap)Superstar</album>
<song>Rock Superstar</song>
<release_year>2000</release_year>
<genre>hip-hop, rap</genre>
</song_id>
<song_id>
<music_group>Red Hot Chili Peppers</music_group>
<album>Californication</album>
<song>Purple Stain</song>
<release_year>1999</release_year>
<genre>alternative</genre>
</song_id>
</major>
</music>
</playlist>
